### ISSUE TITLE
auro-hyperlink doesn't allow relative url's

### ISSUE THREAD

**Issue by johnvoelk** [AlaskaAirlines/ods-hyperlink#28]
## Is your feature request related to a problem? Please describe.

I'm using the following auro-hyperlink with a relative href:

`<auro-hyperlink` href="/shopping">book now</auro-hyperlink>`

 and it always prepends "https://www.alaskaair.com" to it.

## Describe the solution you'd like

I would like it to leave my relative url alone.  The biggest problem is we can't use this on mobile web which has a different hostname (m.alaskaair.com).  The trend is to move away from absolute URL's so we can use different hostname's to run different instances of AS.COM.

## Describe alternatives you've considered

The <ods-hyperlink> does allow relative href's so will use this for now.

**Comment by blackfalcon** [comment]
Can you upgrade to the auro-hyperlink? 

https://github.com/AlaskaAirlines/ods-hyperlink#auro-properties

**Comment by blackfalcon** [comment]
@johnvoelk did the last question help you? Can this issue be closed?

**Comment by johnvoelk** [comment]
Did you fix this in auro-hyperlink?  We have been using the ods hyperlink.
