### ISSUE TITLE
Allow non-HTTP URL schemes (e.g. tel, sms)

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/ods-hyperlink#32]
## Is your feature request related to a problem? Please describe.
I want to use auro-hyperlink with tel: and sms: links, so that interacting with the link calls the phone number or starts composing a text message.

## Describe the solution you'd like
```html
<auro-hyperlink href="tel:+18002527522">Telephone link</auro-hyperlink>
<auro-hyperlink href="sms:82008">SMS link</auro-hyperlink>
```
would produce the following in the shadow root
```html
<a href="tel:+18002527522">Telephone link</a>
<a href="sms:82008">SMS link</auro-hyperlink>
```

Currently it produces the following:
```html
<a class="hyperlink" href="https://+18002527522/">Telephone link</a>
<a class="hyperlink" href="https://0.1.64.88/">SMS link</a>
```

Current workaround is to use auro-button with an onclick that sets window.location.href.

**Comment by blackfalcon** [comment]
Ok, so this isn't so much as feature support, but more so protocol support. E.g. we currently are enforcing a https protocol, and you are asking for tel and SMS. 

Makes sense.
